name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup youtube-dl and yt-dlp
        run: pip install youtube-dl yt-dlp

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Setup cargo-hack
        run: cargo install cargo-hack

      - name: Run tests
        run: cargo hack test --each-feature --exclude-no-default-features
